import {useState} from 'react';
import {ChevronDown,RotateCcw,SlidersHorizontal} from 'lucide-react';
import {DURATIONS,ENVIRONMENTS,WELLNESS_GOALS} from './GeoWellnessData';

const Select=({label,value,options,onChange})=><div className="relative flex-1 min-w-[190px]"><label className="mb-2 block text-[10px] tracking-[.22em] text-[#1E7A3A]/70 uppercase">{label}</label><div className="relative"><select value={value} onChange={e=>onChange(e.target.value)} className="w-full appearance-none rounded-full border border-[#1E7A3A]/20 bg-[#F8F5EE] px-5 py-3.5 pr-10 text-xs text-[#18352A] outline-none transition focus:border-[#C6A75E]">{options.map(o=><option key={o} value={o}>{o==='All'?`Any ${label}`:o}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#C6A75E]"/></div></div>;

export default function GeoWellnessFilters({filters,onChange,count}){
 const [open,setOpen]=useState(false); const active=Object.values(filters).some(v=>v!=='All');
 const reset=()=>onChange({goal:'All',environment:'All',duration:'All'});
 return <section id="discovery" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="flex flex-col gap-6 border-b border-[#1E7A3A]/15 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><span className="text-[10px] tracking-[.32em] text-[#C6A75E] uppercase">DISCOVERY</span><h2 className="mt-3 font-serif text-4xl font-light text-[#123C2A] sm:text-5xl">Find what fits you.</h2></div><button onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-2 self-start rounded-full border border-[#1E7A3A]/20 px-5 py-3 text-[10px] tracking-[.2em] text-[#123C2A] uppercase lg:hidden"><SlidersHorizontal className="h-4 w-4 text-[#C6A75E]"/>Filters</button></div><div className={`${open?'grid':'hidden'} mt-8 gap-4 lg:grid lg:grid-cols-3`}><Select label="Wellness Goal" value={filters.goal} options={WELLNESS_GOALS} onChange={v=>onChange({...filters,goal:v})}/><Select label="Environment" value={filters.environment} options={ENVIRONMENTS} onChange={v=>onChange({...filters,environment:v})}/><Select label="Duration" value={filters.duration} options={DURATIONS} onChange={v=>onChange({...filters,duration:v})}/></div><div className="mt-7 flex items-center justify-between text-[10px] tracking-[.18em] text-[#6B706A] uppercase"><span>{count} curated {count===1?'centre':'centres'}</span>{active&&<button onClick={reset} className="inline-flex items-center gap-2 text-[#1E7A3A] transition hover:text-[#C6A75E]"><RotateCcw className="h-3.5 w-3.5"/>Reset</button>}</div></section>;
}
