import {useMemo,useState} from 'react';
import {ArrowDown,ArrowUpRight,Compass} from 'lucide-react';
import {Link} from 'react-router-dom';
import GeoWellnessCard from './GeoWellnessCard';
import GeoWellnessFilters from './GeoWellnessFilters';
import {GEO_WELLNESS_CENTRES} from './GeoWellnessData';

const reveal='transition duration-700 ease-out';
export default function GeoWellnessCentres(){
 const [filters,setFilters]=useState({goal:'All',environment:'All',duration:'All'});
 const centres=useMemo(()=>GEO_WELLNESS_CENTRES.filter(c=>(filters.goal==='All'||c.goals.includes(filters.goal))&&(filters.environment==='All'||c.environment===filters.environment)&&(filters.duration==='All'||c.durations.includes(filters.duration))),[filters]);
 const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 return <div className="overflow-hidden bg-[#F8F5EE] text-[#18352A]">
  <section id="hero" className="relative flex min-h-[88svh] items-center justify-center overflow-hidden lg:min-h-screen"><img src="https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=2400&q=88" alt="Indian mountain landscape" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#123C2A]/90 via-[#123C2A]/45 to-[#123C2A]/20"/><div className="relative z-10 mx-auto max-w-5xl px-5 pt-24 text-center sm:px-8"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-[9px] tracking-[.28em] text-[#F8F5EE] uppercase backdrop-blur-md"><Compass className="h-3.5 w-3.5 text-[#C6A75E]"/>DARSHAI GEO-WELLNESS</div><h1 className="mt-7 font-serif text-5xl font-light leading-[1.08] tracking-[-.02em] text-[#F8F5EE] sm:text-6xl lg:text-[78px]">Curated Geo-Wellness<br className="hidden sm:block"/> Centres Across India</h1><p className="mx-auto mt-6 max-w-2xl text-sm font-light leading-7 text-[#F1ECE2]/90 sm:text-lg">Discover wellness experiences shaped by people, place and purpose.</p><div className="mt-9 flex flex-col items-center justify-center gap-4 sm:flex-row"><Link to="/begin-your-journey" className="inline-flex items-center gap-2 rounded-full bg-[#F8F5EE] px-7 py-4 text-[10px] font-medium tracking-[.23em] text-[#123C2A] uppercase transition hover:bg-white">Begin your journey <ArrowUpRight className="h-4 w-4 text-[#1E7A3A]"/></Link><button onClick={()=>scroll('discovery')} className="text-[10px] font-medium tracking-[.23em] text-[#F8F5EE] uppercase transition hover:text-[#C6A75E]">Explore centres →</button></div></div><button onClick={()=>scroll('idea')} className="absolute bottom-7 left-1/2 z-10 -translate-x-1/2 text-center text-[#F8F5EE]/75"><span className="block text-[9px] tracking-[.3em] uppercase">Place matters</span><span className="mx-auto mt-2 flex h-7 w-7 items-center justify-center rounded-full border border-white/25"><ArrowDown className="h-3.5 w-3.5"/></span></button></section>
  <section id="idea" className="relative flex min-h-[62vh] items-center justify-center bg-[#F1ECE2] px-5 py-28 text-center sm:px-8 lg:min-h-[70vh]"><div className="absolute inset-x-0 top-1/2 h-px bg-[#C6A75E]/10"/><div className="relative max-w-5xl"><span className="mx-auto mb-10 block h-px w-10 bg-[#C6A75E]"/><h2 className="font-serif text-5xl font-light leading-[1.08] tracking-[-.02em] text-[#123C2A] sm:text-6xl lg:text-[78px]">“Where you are<br className="hidden sm:block"/> is part of the journey.”</h2><p className="mx-auto mt-8 max-w-2xl text-sm font-light leading-7 text-[#6B706A] sm:text-lg">DARSHAI considers the environment, experience and individual — not just the destination.</p></div></section>
  <section id="curation" className="bg-[#F8F5EE] px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl"><span className="text-[10px] tracking-[.32em] text-[#C6A75E] uppercase">WHY DARSHAI</span><h2 className="mt-4 max-w-3xl font-serif text-4xl font-light leading-tight text-[#123C2A] sm:text-6xl">Not every centre<br/>is right for every journey.</h2><div className="mt-16 grid gap-10 md:grid-cols-2 lg:grid-cols-4 lg:gap-8">{[['01','CURATED','Carefully selected wellness partners.','Authenticity, geography and experience.'],['02','QUALIFIED','Wellness professionals reviewed during onboarding.','People and practices matter.'],['03','TRANSPARENT','Programs, accommodation and inclusions clearly documented.','Clarity before commitment.'],['04','ENVIRONMENT-FIRST','Location and surroundings are part of the experience.','Place shapes the experience.']].map(([n,t,s,d])=><div key={n} className="border-t border-[#C6A75E]/50 pt-5"><div className="flex justify-between"><span className="font-serif text-2xl text-[#C6A75E]">{n}</span><span className="text-[9px] tracking-[.25em] text-[#6B706A]">PRINCIPLE</span></div><h3 className="mt-8 text-[11px] font-medium tracking-[.25em] text-[#1E7A3A] uppercase">{t}</h3><p className="mt-4 font-serif text-xl font-light leading-snug text-[#123C2A]">“{s}”</p><p className="mt-7 border-t border-[#1E7A3A]/10 pt-4 text-xs leading-6 text-[#6B706A]">{d}</p></div>)}</div></div></section>
  <section id="centres" className="bg-[#F8F5EE] px-5 pb-28 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="mb-12"><span className="text-[10px] tracking-[.32em] text-[#C6A75E] uppercase">THE CURATED COLLECTION</span><h2 className="mt-3 font-serif text-4xl font-light text-[#123C2A] sm:text-6xl">Explore the collection</h2><p className="mt-3 text-sm font-light text-[#6B706A] sm:text-base">Three environments. Different journeys.</p></div><div className="grid gap-7 lg:grid-cols-3">{centres.map((centre,i)=><GeoWellnessCard key={centre.id} centre={centre} index={i}/>)}</div>{!centres.length&&<div className="rounded-[28px] border border-[#1E7A3A]/15 bg-[#F1ECE2] px-6 py-16 text-center"><h3 className="font-serif text-3xl text-[#123C2A]">Nothing matches these preferences.</h3><button onClick={()=>setFilters({goal:'All',environment:'All',duration:'All'})} className="mt-6 rounded-full bg-[#123C2A] px-6 py-3 text-[10px] tracking-[.2em] text-[#F8F5EE] uppercase">Reset discovery</button></div>}</div></section>
  <GeoWellnessFilters filters={filters} onChange={setFilters} count={centres.length}/>
  <section id="environment" className="relative flex min-h-[72vh] items-center justify-center overflow-hidden"><img src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2400&q=85" alt="Coastal wellness environment" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[#123C2A]/70"/><div className="relative max-w-5xl px-5 py-28 text-center sm:px-8"><span className="text-[10px] tracking-[.34em] text-[#C6A75E] uppercase">ENVIRONMENT AS MEDICINE</span><h2 className="mt-8 font-serif text-5xl font-light leading-[1.08] text-[#F8F5EE] sm:text-6xl lg:text-[76px]">Coastal. Forest. Mountain.<br/>Heritage. Urban. Retreat.</h2><p className="mt-10 text-base font-light text-[#F1ECE2]/90 sm:text-lg">Different places create different experiences.</p></div></section>
  <section className="bg-[#F1ECE2] px-5 py-28 text-center sm:px-8 lg:py-36"><span className="mx-auto block h-px w-8 bg-[#C6A75E]"/><h2 className="mt-8 font-serif text-4xl font-light text-[#123C2A] sm:text-6xl">Not sure where to begin?</h2><p className="mx-auto mt-5 max-w-xl text-sm font-light leading-7 text-[#6B706A] sm:text-lg">Tell us what you are looking for. DARSHAI can help you explore suitable wellness environments.</p><div className="mt-9 flex flex-col justify-center gap-4 sm:flex-row"><Link to="/begin-your-journey" className="rounded-full bg-[#123C2A] px-7 py-4 text-[10px] tracking-[.22em] text-[#F8F5EE] uppercase transition hover:bg-[#1E7A3A]">Begin your journey ↗</Link><button onClick={()=>scroll('centres')} className="rounded-full border border-[#1E7A3A]/25 px-7 py-4 text-[10px] tracking-[.22em] text-[#123C2A] uppercase transition hover:border-[#C6A75E]">View all centres</button></div></section>
  <section className="relative overflow-hidden bg-[#123C2A] px-5 py-32 text-center sm:px-8 lg:py-48"><img src="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=2400&q=80" alt="Forest canopy" className="absolute inset-0 h-full w-full object-cover opacity-20 grayscale"/><div className="absolute inset-0 bg-[#123C2A]/80"/><div className="relative mx-auto max-w-5xl"><span className="text-[10px] tracking-[.34em] text-[#C6A75E] uppercase">AN ENVIRONMENT-FIRST PHILOSOPHY</span><h2 className="mt-8 font-serif text-5xl font-light leading-[1.08] text-[#F8F5EE] sm:text-6xl lg:text-[76px]">Your wellness journey<br/>shouldn't start with a destination.<br/>It should start with you.</h2><span className="mx-auto my-9 block h-px w-28 bg-[#C6A75E]"/><p className="mx-auto max-w-xl text-base font-light leading-7 text-[#F1ECE2]/85">Explore a more personalized Geo-Wellness journey with DARSHAI.</p><Link to="/begin-your-journey" className="mt-10 inline-flex rounded-full bg-[#F8F5EE] px-8 py-4 text-[10px] tracking-[.24em] text-[#123C2A] uppercase transition hover:bg-white">Begin your journey ↗</Link></div></section>
 </div>;
}
